### ISSUE TITLE
Incomplete successor/predecessor list for undirected networks

### ISSUE THREAD

**Issue by IngoScholtes** [pathpy/pathpy#12]
In an undirected network, the list of successors/predecessors is incomplete. Consider the following example: 

```
>>> n = pp.Network(directed=False)
>>> n.add_edge('a', 'b')
>>> n.add_edge('b', 'c')
>>> n.add_edge('a', 'c')
>>> n.add_edge('b', 'd')
>>> n.add_edge('d', 'f')
>>> n.add_edge('d', 'g')
>>> n.add_edge('d', 'e')
>>> n.add_edge('e', 'f')
>>> n.add_edge('f', 'g')
>>> print(n.nodes.successors['b'])
>>> print(n.nodes.predecessors['b'])
{'c': Node c, 'd': Node d}
{'a': Node a}
```

In an undirected network, the list of successors and predecessors should be identical, i.e. each method should return the union of both.

**Comment by IngoScholtes** [comment]
The current solutions leads to a number of downstream problems, e.g. it requires a distinction between directed/undirected networks whenever the successors/predecessors list is used.

**Comment by hackl** [comment]
Now successors and predecessors are network properties. A distinction is made between directed and undirected networks.

```python
>>> import pathpy as pp
>>> n = pp.Network(directed=False)
>>> n.add_edge('a', 'b')
>>> n.add_edge('b', 'c')
>>> n.add_edge('a', 'c')
>>> n.add_edge('b', 'd')
>>> n.add_edge('d', 'f')
>>> n.add_edge('d', 'g')
>>> n.add_edge('d', 'e')
>>> n.add_edge('e', 'f')
>>> n.add_edge('f', 'g')
>>> print(n.successors['b'])
>>> print(n.predecessors['b'])
{'c': Node c, 'd': Node d, 'a': Node a}
{'c': Node c, 'd': Node d, 'a': Node a}
```

Now a ``dict`` of ``dict`` is returned, different to the ``n.nodes.successors`` where a ``defaultdict`` is returned. I.e all nodes are listed in the ``dict`` even if they don't have successors or predecessors.

**Comment by IngoScholtes** [comment]
Thanks! Is it correct that there is still `network.nodes.successors` with the old behaviour?

**Comment by hackl** [comment]
Yes, in order to keep the construction process from the directed to the indirect network and allow a simple mapping between both. (If required we can change this behaviour and return the same as ``network.successors``.)

**Comment by IngoScholtes** [comment]
Yes, we should do that, because it is easy to mistake the two. I have some code using `network.nodes.successor` that is now incorrect unless I change to `network.successors`. If the name is the same so should be the semantics.

**Comment by IngoScholtes** [comment]
fixed in restructured core
