### ISSUE TITLE
Qusetions about the TemporalNetwork class in pathpy3

### ISSUE THREAD

**Issue by jiaxucode** [pathpy/pathpy#136]
When I run the [eurocss2019-tutorial] project by pathpy3, I find the code occurs a bugs
`t = pp.TemporalNetwork.read_file('data/temporal_clusters.tedges')`
It shows the the TemporalNetwork class does not have read_file() function. How to fix the problem when I want to read real-world datasets?

**Comment by IngoScholtes** [comment]
Sorry for the last response. This is due to the fact that the tutorial code uses pathpy2, not pathpy3. Please install `pathpy2` via pip or from [this repository](https://github.com/uzhdag/pathpy).
