### ISSUE TITLE
Network visualisation in VS Code

### ISSUE THREAD

**Issue by IngoScholtes** [pathpy/pathpy#2]
Due to the lack of require.js, the d3js visualisations are currently not working in VS Code.

**Comment by hackl** [comment]
Network visualisation returns now a single instance of the network. However, the first network has to be plotted twice. In the first run, the d3js library is loaded, in the second run, the network is plotted. This behaviour only occurs in VS Code. Jupyter Notebook and Jupyter Lab work fine, without plotting twice.

**Comment by IngoScholtes** [comment]
fixed in latest restructuring of visualisation model
