### ISSUE TITLE
Handling of edge frequency attribute

### ISSUE THREAD

**Issue by IngoScholtes** [pathpy/pathpy#28]
From today's discussion, I understood that the weight attributes of edges will be overwritten when calling `add_edge`, while the frequency attributes of edges will be automatically summed. However, this example shows that this is currently not the case:

````
>>> n = pp.Network()
>>> n.add_edge('a', 'b', frequency=1)
>>> n.add_edge('a', 'b', frequency=5)
>>> print(n.edges['a-b']['frequency'])
5
``

**Comment by hackl** [comment]
Currently, the frequency of an edge in a network is a property of the network and not of the edge.

``` python
>>> import pathpy as pp
>>> n = pp.Network()
>>> n.add_edge('a', 'b', frequency=1)
>>> n.add_edge('a', 'b', frequency=5)
>>> print(n.edges.counter())
Counter({'a-b': 6})
```

**Comment by IngoScholtes** [comment]
fixed with restructured core
