### ISSUE TITLE
id_as_label property is ignored by tikz backend 

### ISSUE THREAD

**Issue by IngoScholtes** [pathpy/pathpy#39]
Use of custom node labels currently does not work in tikz, e.g. the following network is visualised with proper node labels in html but not in tikz. It seems the `id_as_label` property is always set to default value of True: 

```
n = pp.Network(directed = False)
n.add_edge('a', 'b')
n.add_edge('b', 'a')
plot_style['id_as_label'] = False
plot_style['node_label'] = {'a': 'x', 'b': 'y'}
n.plot('example.tex', **plot_style)
```

**Comment by hackl** [comment]
``id_as_label`` can be used for edges and nodes. Hence, in order to disable the option for nodes, the following command should be used:

```python
plot_style['node_id_as_label'] = False
```

and for edges

```python
plot_style['edge_id_as_label'] = False
```

**Comment by IngoScholtes** [comment]
Thanks, Jürgen. I can confirm that this works as expected.
