### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by IngoScholtes** [pathpy/pathpy#5]
Here's some thoughts on features that would make the implementation of network algorithms in `pathpy3` easier and more convenient:

- [ ] Add a `degree` function (weighted/directed) to `Node` class
- [ ] Add `successors`/`predecessors` atrributes to `Node` class
- [ ] Add method to simplify the mapping of nodes/edges to adjacency matrix indices (this is a very common task)
- [ ] Consider adding a reference to the `Network` class to `Node` and `Edge`
- [ ] Shorten names of `number_of_nodes` and `number_of_edges`
- [ ] Add `degree_sequence` and `degree_distribution` properties (weighted/directed) to `Network` class or external functions to calculate degrees
- [ ] Add functions to quickly find nodes/edges in a network with given property values (including expressions for smaller/larger/equal/etc.)
- [ ] Use output of `summary()` as default `__str__` representation
- [ ] Fix string representations on console if logging is deactivated (missing line breaks)

**Comment by hackl** [comment]
I moved the feature requests to the Project board of github for better management.
