### ISSUE TITLE
"begin time" and "end time" of a temporal network

### ISSUE THREAD

**Issue by user1246638** [pathpy/pathpy#68]
Something to discuss:

Should temporal network have a "begin time" and "end time", for the information when the measurement started and ended?
It really feels that way. Check out this example:

measured:
source| target| timestamp
-------|----- | -------------
a| b| 3
b| c| 10
---------------

If our measurement started at 0, and ended at 15, this is not the same as if we measured from 0 until 150. In the latter case we would say that the network is much sparser.

**Comment by IngoScholtes** [comment]
This has been integrated in the latest version of pathpy. Edges in a temporal network can now have a `timestamp` attribute (for instantaneous edges) or a `begin`/`end` attribute for edges observed during a specific time period.
