### ISSUE TITLE
Value error while loading path collection (frequency =True)

### ISSUE THREAD

**Issue by VincenzoPerri** [pathpy/pathpy#69]
loading from:
```
a,c,d,10.0
b,c,e,10.0
```
 
using:
`pp.io.csv.read_pathcollection('../data/toy_paths.ngram', frequency=True)`

returns the following ValueError:
`ValueError: invalid literal for int() with base 10: '10.0'`

**Comment by hackl** [comment]
Instead of int, now float values are assumed for the frequencies.
