### ISSUE TITLE
HigherOrderNetwork class doesn't allow to generate null model

### ISSUE THREAD

**Issue by VincenzoPerri** [pathpy/pathpy#70]

**Comment by hackl** [comment]
NullModel is not supported yet. Also, the NullModel will be a separate class in pathpy3

**Comment by hackl** [comment]
`NullModel` is now a new class in pathpy which is a child from the `HigherOrderNetwork` class. NullModels can now be generated based on paths or networks, edges of the `HigherOrderNetwork`, as well as the `NullModel`, have the attributes `observed` and `possible` which correspond to the previous np.array in pathpy2.

```python
>>> import pathpy as pp

>>> paths = pp.PathCollection()
>>> paths.add('a', 'c', 'd', uid='a-c-d', frequency=10)
>>> paths.add('b', 'c', 'e', uid='b-c-e', frequency=10)

>>> null = NullModel.from_paths(paths, order=2)
>>> null.number_of_edges()
4

>>> null.number_of_nodes()
4

>>> for e in null.edges:
>>>     print(e['observed'])
5.0
5.0
5.0
5.0

```
