### ISSUE TITLE
Mapping nodes to matrix indices

### ISSUE THREAD

**Issue by VincenzoPerri** [pathpy/pathpy#71]
There is currently no attribute that maps nodes to the corresponding indices in the network matrices

**Comment by hackl** [comment]
This is done with the node and edge property index, which returns a dict with node uids and indices.

```python
>>> from pathpy import Network
>>> net = Network()
>>> net.add_edge('a', 'b', uid='ab')
>>> print(net.nodes.index)
{'a': 0, 'b': 1}
```
